package com.konfigthis.client;

import com.konfigthis.client.api.BusinessEntitiesApi;
import com.konfigthis.client.api.BusinessUnitsApi;
import com.konfigthis.client.api.CustomFieldDefinitionsApi;
import com.konfigthis.client.api.DefaultRemunerationComponentsApi;
import com.konfigthis.client.api.EmploymentConditionsApi;
import com.konfigthis.client.api.EndJobApi;
import com.konfigthis.client.api.ExtendedLeaveApi;
import com.konfigthis.client.api.ExtendedLeaveTypesApi;
import com.konfigthis.client.api.FormsApi;
import com.konfigthis.client.api.JobChangeReasonsApi;
import com.konfigthis.client.api.JobRequirementGroupsApi;
import com.konfigthis.client.api.JobTimelineApi;
import com.konfigthis.client.api.JobsApi;
import com.konfigthis.client.api.LocationsApi;
import com.konfigthis.client.api.PayGradesApi;
import com.konfigthis.client.api.PeopleApi;
import com.konfigthis.client.api.PeopleDocumentsApi;
import com.konfigthis.client.api.PeopleImagesApi;
import com.konfigthis.client.api.PeopleSkillsApi;
import com.konfigthis.client.api.PermissionGroupsApi;
import com.konfigthis.client.api.PersonDocumentsDeprecatedApi;
import com.konfigthis.client.api.PositionTitlesApi;
import com.konfigthis.client.api.QualificationInstancesApi;
import com.konfigthis.client.api.QualificationLibraryItemsApi;
import com.konfigthis.client.api.QualificationStatusesApi;
import com.konfigthis.client.api.QualificationTypesApi;
import com.konfigthis.client.api.RecruitmentSourcesApi;
import com.konfigthis.client.api.RepresentativeTypesApi;
import com.konfigthis.client.api.SkillDisciplinesApi;
import com.konfigthis.client.api.SkillsApi;
import com.konfigthis.client.api.TrainingProvidersApi;
import com.konfigthis.client.api.TrainingStatusesApi;
import com.konfigthis.client.api.TrainingTypesApi;
import com.konfigthis.client.api.TrainingsApi;
import com.konfigthis.client.api.UsersApi;
import com.konfigthis.client.api.WebhookEventsApi;
import com.konfigthis.client.api.WebhooksApi;
import com.konfigthis.client.api.WorkClassesApi;
import com.konfigthis.client.api.WorkRightsApi;
import com.konfigthis.client.api.WorkTypesApi;
import com.konfigthis.client.api.WorkflowEventsApi;
import com.konfigthis.client.api.WorkflowsApi;

public class IntelliHr {
    private ApiClient apiClient;
    public final BusinessEntitiesApi businessEntities;
    public final BusinessUnitsApi businessUnits;
    public final CustomFieldDefinitionsApi customFieldDefinitions;
    public final DefaultRemunerationComponentsApi defaultRemunerationComponents;
    public final EmploymentConditionsApi employmentConditions;
    public final EndJobApi endJob;
    public final ExtendedLeaveApi extendedLeave;
    public final ExtendedLeaveTypesApi extendedLeaveTypes;
    public final FormsApi forms;
    public final JobChangeReasonsApi jobChangeReasons;
    public final JobRequirementGroupsApi jobRequirementGroups;
    public final JobTimelineApi jobTimeline;
    public final JobsApi jobs;
    public final LocationsApi locations;
    public final PayGradesApi payGrades;
    public final PeopleApi people;
    public final PeopleDocumentsApi peopleDocuments;
    public final PeopleImagesApi peopleImages;
    public final PeopleSkillsApi peopleSkills;
    public final PermissionGroupsApi permissionGroups;
    public final PersonDocumentsDeprecatedApi personDocumentsDeprecated;
    public final PositionTitlesApi positionTitles;
    public final QualificationInstancesApi qualificationInstances;
    public final QualificationLibraryItemsApi qualificationLibraryItems;
    public final QualificationStatusesApi qualificationStatuses;
    public final QualificationTypesApi qualificationTypes;
    public final RecruitmentSourcesApi recruitmentSources;
    public final RepresentativeTypesApi representativeTypes;
    public final SkillDisciplinesApi skillDisciplines;
    public final SkillsApi skills;
    public final TrainingProvidersApi trainingProviders;
    public final TrainingStatusesApi trainingStatuses;
    public final TrainingTypesApi trainingTypes;
    public final TrainingsApi trainings;
    public final UsersApi users;
    public final WebhookEventsApi webhookEvents;
    public final WebhooksApi webhooks;
    public final WorkClassesApi workClasses;
    public final WorkRightsApi workRights;
    public final WorkTypesApi workTypes;
    public final WorkflowEventsApi workflowEvents;
    public final WorkflowsApi workflows;

    public IntelliHr() {
        this(null);
    }

    public IntelliHr(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.businessEntities = new BusinessEntitiesApi(this.apiClient);
        this.businessUnits = new BusinessUnitsApi(this.apiClient);
        this.customFieldDefinitions = new CustomFieldDefinitionsApi(this.apiClient);
        this.defaultRemunerationComponents = new DefaultRemunerationComponentsApi(this.apiClient);
        this.employmentConditions = new EmploymentConditionsApi(this.apiClient);
        this.endJob = new EndJobApi(this.apiClient);
        this.extendedLeave = new ExtendedLeaveApi(this.apiClient);
        this.extendedLeaveTypes = new ExtendedLeaveTypesApi(this.apiClient);
        this.forms = new FormsApi(this.apiClient);
        this.jobChangeReasons = new JobChangeReasonsApi(this.apiClient);
        this.jobRequirementGroups = new JobRequirementGroupsApi(this.apiClient);
        this.jobTimeline = new JobTimelineApi(this.apiClient);
        this.jobs = new JobsApi(this.apiClient);
        this.locations = new LocationsApi(this.apiClient);
        this.payGrades = new PayGradesApi(this.apiClient);
        this.people = new PeopleApi(this.apiClient);
        this.peopleDocuments = new PeopleDocumentsApi(this.apiClient);
        this.peopleImages = new PeopleImagesApi(this.apiClient);
        this.peopleSkills = new PeopleSkillsApi(this.apiClient);
        this.permissionGroups = new PermissionGroupsApi(this.apiClient);
        this.personDocumentsDeprecated = new PersonDocumentsDeprecatedApi(this.apiClient);
        this.positionTitles = new PositionTitlesApi(this.apiClient);
        this.qualificationInstances = new QualificationInstancesApi(this.apiClient);
        this.qualificationLibraryItems = new QualificationLibraryItemsApi(this.apiClient);
        this.qualificationStatuses = new QualificationStatusesApi(this.apiClient);
        this.qualificationTypes = new QualificationTypesApi(this.apiClient);
        this.recruitmentSources = new RecruitmentSourcesApi(this.apiClient);
        this.representativeTypes = new RepresentativeTypesApi(this.apiClient);
        this.skillDisciplines = new SkillDisciplinesApi(this.apiClient);
        this.skills = new SkillsApi(this.apiClient);
        this.trainingProviders = new TrainingProvidersApi(this.apiClient);
        this.trainingStatuses = new TrainingStatusesApi(this.apiClient);
        this.trainingTypes = new TrainingTypesApi(this.apiClient);
        this.trainings = new TrainingsApi(this.apiClient);
        this.users = new UsersApi(this.apiClient);
        this.webhookEvents = new WebhookEventsApi(this.apiClient);
        this.webhooks = new WebhooksApi(this.apiClient);
        this.workClasses = new WorkClassesApi(this.apiClient);
        this.workRights = new WorkRightsApi(this.apiClient);
        this.workTypes = new WorkTypesApi(this.apiClient);
        this.workflowEvents = new WorkflowEventsApi(this.apiClient);
        this.workflows = new WorkflowsApi(this.apiClient);
    }

}
