/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CustomFieldsResponse;
import com.konfigthis.client.model.DataPropertyInnerAddressesInner;
import com.konfigthis.client.model.DataPropertyInnerEmailAddressesInner;
import com.konfigthis.client.model.DataPropertyInnerEmergencyContact;
import com.konfigthis.client.model.DataPropertyInnerJobsInner;
import com.konfigthis.client.model.DataPropertyInnerMedicalConditionsInner;
import com.konfigthis.client.model.DataPropertyInnerPhoneNumbersInner;
import com.konfigthis.client.model.DataPropertyInnerWorkRights;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataPropertyInner
 */
public class DataPropertyInnerTest {
    private final DataPropertyInner model = new DataPropertyInner();

    /**
     * Model tests for DataPropertyInner
     */
    @Test
    public void testDataPropertyInner() {
        // TODO: test DataPropertyInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'preferredName'
     */
    @Test
    public void preferredNameTest() {
        // TODO: test preferredName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'isSupervisor'
     */
    @Test
    public void isSupervisorTest() {
        // TODO: test isSupervisor
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'autoIncrementIntellihrId'
     */
    @Test
    public void autoIncrementIntellihrIdTest() {
        // TODO: test autoIncrementIntellihrId
    }

    /**
     * Test the property 'medicalConditions'
     */
    @Test
    public void medicalConditionsTest() {
        // TODO: test medicalConditions
    }

    /**
     * Test the property 'emailAddresses'
     */
    @Test
    public void emailAddressesTest() {
        // TODO: test emailAddresses
    }

    /**
     * Test the property 'emergencyContact'
     */
    @Test
    public void emergencyContactTest() {
        // TODO: test emergencyContact
    }

    /**
     * Test the property 'employmentStatus'
     */
    @Test
    public void employmentStatusTest() {
        // TODO: test employmentStatus
    }

    /**
     * Test the property 'jobs'
     */
    @Test
    public void jobsTest() {
        // TODO: test jobs
    }

    /**
     * Test the property 'workRights'
     */
    @Test
    public void workRightsTest() {
        // TODO: test workRights
    }

    /**
     * Test the property 'primaryEmailAddress'
     */
    @Test
    public void primaryEmailAddressTest() {
        // TODO: test primaryEmailAddress
    }

    /**
     * Test the property 'primaryPhoneNumber'
     */
    @Test
    public void primaryPhoneNumberTest() {
        // TODO: test primaryPhoneNumber
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    public void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

    /**
     * Test the property 'userAccount'
     */
    @Test
    public void userAccountTest() {
        // TODO: test userAccount
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
