/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.QualificationInstancePropertyLibraryItemQualificationType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for QualificationInstancePropertyLibraryItem
 */
public class QualificationInstancePropertyLibraryItemTest {
    private final QualificationInstancePropertyLibraryItem model = new QualificationInstancePropertyLibraryItem();

    /**
     * Model tests for QualificationInstancePropertyLibraryItem
     */
    @Test
    public void testQualificationInstancePropertyLibraryItem() {
        // TODO: test QualificationInstancePropertyLibraryItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'qualificationType'
     */
    @Test
    public void qualificationTypeTest() {
        // TODO: test qualificationType
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

}
