/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PayGradeUpdateRequestPayStepsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayGradeUpdateRequestPayStepsInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PERMANENT_HOURLY_RATE = "permanentHourlyRate";
  @SerializedName(SERIALIZED_NAME_PERMANENT_HOURLY_RATE)
  private Double permanentHourlyRate;

  public static final String SERIALIZED_NAME_PERMANENT_HOURLY_RATE_CURRENCY = "permanentHourlyRateCurrency";
  @SerializedName(SERIALIZED_NAME_PERMANENT_HOURLY_RATE_CURRENCY)
  private String permanentHourlyRateCurrency;

  public static final String SERIALIZED_NAME_CASUAL_HOURLY_RATE = "casualHourlyRate";
  @SerializedName(SERIALIZED_NAME_CASUAL_HOURLY_RATE)
  private Double casualHourlyRate;

  public static final String SERIALIZED_NAME_CASUAL_HOURLY_RATE_CURRENCY = "casualHourlyRateCurrency";
  @SerializedName(SERIALIZED_NAME_CASUAL_HOURLY_RATE_CURRENCY)
  private String casualHourlyRateCurrency;

  public static final String SERIALIZED_NAME_ANNUAL_SALARY = "annualSalary";
  @SerializedName(SERIALIZED_NAME_ANNUAL_SALARY)
  private Double annualSalary;

  public static final String SERIALIZED_NAME_ANNUAL_SALARY_CURRENCY = "annualSalaryCurrency";
  @SerializedName(SERIALIZED_NAME_ANNUAL_SALARY_CURRENCY)
  private String annualSalaryCurrency;

  public PayGradeUpdateRequestPayStepsInner() {
  }

  public PayGradeUpdateRequestPayStepsInner id(String id) {
    
    
    if (id != null && id.length() < 36) {
      throw new IllegalArgumentException("Invalid value for id. Length must be greater than or equal to 36.");
    }
    
    this.id = id;
    return this;
  }

   /**
   * The identifier string for the Pay Grade Step.  Providing an &#x60;id&#x60; will update an existing step.  Not providing an &#x60;id&#x60; will create a new step under the Pay Grade..
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8a5f3ea6-ea6b-4425-8a87-3c256bb7b6f9", value = "The identifier string for the Pay Grade Step.  Providing an `id` will update an existing step.  Not providing an `id` will create a new step under the Pay Grade..")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    if (id != null && id.length() < 36) {
      throw new IllegalArgumentException("Invalid value for id. Length must be greater than or equal to 36.");
    }
    this.id = id;
  }


  public PayGradeUpdateRequestPayStepsInner name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name assigned to this [Pay Grade](https://developers.intellihr.io/docs/v1/) Step.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Level 1", value = "The name assigned to this [Pay Grade](https://developers.intellihr.io/docs/v1/) Step.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public PayGradeUpdateRequestPayStepsInner permanentHourlyRate(Double permanentHourlyRate) {
    
    
    
    
    this.permanentHourlyRate = permanentHourlyRate;
    return this;
  }

  public PayGradeUpdateRequestPayStepsInner permanentHourlyRate(Integer permanentHourlyRate) {
    
    
    
    
    this.permanentHourlyRate = permanentHourlyRate.doubleValue();
    return this;
  }

   /**
   * Stores the hourly rate for permanent [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.
   * @return permanentHourlyRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25.5", value = "Stores the hourly rate for permanent [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.")

  public Double getPermanentHourlyRate() {
    return permanentHourlyRate;
  }


  public void setPermanentHourlyRate(Double permanentHourlyRate) {
    
    
    
    this.permanentHourlyRate = permanentHourlyRate;
  }


  public PayGradeUpdateRequestPayStepsInner permanentHourlyRateCurrency(String permanentHourlyRateCurrency) {
    
    
    
    
    this.permanentHourlyRateCurrency = permanentHourlyRateCurrency;
    return this;
  }

   /**
   * The currency that the permanentHourlyRate is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
   * @return permanentHourlyRateCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "AUD", value = "The currency that the permanentHourlyRate is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).")

  public String getPermanentHourlyRateCurrency() {
    return permanentHourlyRateCurrency;
  }


  public void setPermanentHourlyRateCurrency(String permanentHourlyRateCurrency) {
    
    
    
    this.permanentHourlyRateCurrency = permanentHourlyRateCurrency;
  }


  public PayGradeUpdateRequestPayStepsInner casualHourlyRate(Double casualHourlyRate) {
    
    
    
    
    this.casualHourlyRate = casualHourlyRate;
    return this;
  }

  public PayGradeUpdateRequestPayStepsInner casualHourlyRate(Integer casualHourlyRate) {
    
    
    
    
    this.casualHourlyRate = casualHourlyRate.doubleValue();
    return this;
  }

   /**
   * Stores the hourly rate for casual [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.
   * @return casualHourlyRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25.5", value = "Stores the hourly rate for casual [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.")

  public Double getCasualHourlyRate() {
    return casualHourlyRate;
  }


  public void setCasualHourlyRate(Double casualHourlyRate) {
    
    
    
    this.casualHourlyRate = casualHourlyRate;
  }


  public PayGradeUpdateRequestPayStepsInner casualHourlyRateCurrency(String casualHourlyRateCurrency) {
    
    
    
    
    this.casualHourlyRateCurrency = casualHourlyRateCurrency;
    return this;
  }

   /**
   * The currency that the casualHourlyRate is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
   * @return casualHourlyRateCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "AUD", value = "The currency that the casualHourlyRate is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).")

  public String getCasualHourlyRateCurrency() {
    return casualHourlyRateCurrency;
  }


  public void setCasualHourlyRateCurrency(String casualHourlyRateCurrency) {
    
    
    
    this.casualHourlyRateCurrency = casualHourlyRateCurrency;
  }


  public PayGradeUpdateRequestPayStepsInner annualSalary(Double annualSalary) {
    
    
    
    
    this.annualSalary = annualSalary;
    return this;
  }

  public PayGradeUpdateRequestPayStepsInner annualSalary(Integer annualSalary) {
    
    
    
    
    this.annualSalary = annualSalary.doubleValue();
    return this;
  }

   /**
   * Stores the annual salary for [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.
   * @return annualSalary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25.5", value = "Stores the annual salary for [Jobs](https://developers.intellihr.io/docs/v1/) for this Step.")

  public Double getAnnualSalary() {
    return annualSalary;
  }


  public void setAnnualSalary(Double annualSalary) {
    
    
    
    this.annualSalary = annualSalary;
  }


  public PayGradeUpdateRequestPayStepsInner annualSalaryCurrency(String annualSalaryCurrency) {
    
    
    
    
    this.annualSalaryCurrency = annualSalaryCurrency;
    return this;
  }

   /**
   * The currency that the annualSalary is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
   * @return annualSalaryCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "AUD", value = "The currency that the annualSalary is being paid in. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).")

  public String getAnnualSalaryCurrency() {
    return annualSalaryCurrency;
  }


  public void setAnnualSalaryCurrency(String annualSalaryCurrency) {
    
    
    
    this.annualSalaryCurrency = annualSalaryCurrency;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayGradeUpdateRequestPayStepsInner instance itself
   */
  public PayGradeUpdateRequestPayStepsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayGradeUpdateRequestPayStepsInner payGradeUpdateRequestPayStepsInner = (PayGradeUpdateRequestPayStepsInner) o;
    return Objects.equals(this.id, payGradeUpdateRequestPayStepsInner.id) &&
        Objects.equals(this.name, payGradeUpdateRequestPayStepsInner.name) &&
        Objects.equals(this.permanentHourlyRate, payGradeUpdateRequestPayStepsInner.permanentHourlyRate) &&
        Objects.equals(this.permanentHourlyRateCurrency, payGradeUpdateRequestPayStepsInner.permanentHourlyRateCurrency) &&
        Objects.equals(this.casualHourlyRate, payGradeUpdateRequestPayStepsInner.casualHourlyRate) &&
        Objects.equals(this.casualHourlyRateCurrency, payGradeUpdateRequestPayStepsInner.casualHourlyRateCurrency) &&
        Objects.equals(this.annualSalary, payGradeUpdateRequestPayStepsInner.annualSalary) &&
        Objects.equals(this.annualSalaryCurrency, payGradeUpdateRequestPayStepsInner.annualSalaryCurrency)&&
        Objects.equals(this.additionalProperties, payGradeUpdateRequestPayStepsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, permanentHourlyRate, permanentHourlyRateCurrency, casualHourlyRate, casualHourlyRateCurrency, annualSalary, annualSalaryCurrency, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayGradeUpdateRequestPayStepsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    permanentHourlyRate: ").append(toIndentedString(permanentHourlyRate)).append("\n");
    sb.append("    permanentHourlyRateCurrency: ").append(toIndentedString(permanentHourlyRateCurrency)).append("\n");
    sb.append("    casualHourlyRate: ").append(toIndentedString(casualHourlyRate)).append("\n");
    sb.append("    casualHourlyRateCurrency: ").append(toIndentedString(casualHourlyRateCurrency)).append("\n");
    sb.append("    annualSalary: ").append(toIndentedString(annualSalary)).append("\n");
    sb.append("    annualSalaryCurrency: ").append(toIndentedString(annualSalaryCurrency)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("permanentHourlyRate");
    openapiFields.add("permanentHourlyRateCurrency");
    openapiFields.add("casualHourlyRate");
    openapiFields.add("casualHourlyRateCurrency");
    openapiFields.add("annualSalary");
    openapiFields.add("annualSalaryCurrency");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayGradeUpdateRequestPayStepsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayGradeUpdateRequestPayStepsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayGradeUpdateRequestPayStepsInner is not found in the empty JSON string", PayGradeUpdateRequestPayStepsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("permanentHourlyRateCurrency") != null && !jsonObj.get("permanentHourlyRateCurrency").isJsonNull()) && !jsonObj.get("permanentHourlyRateCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `permanentHourlyRateCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("permanentHourlyRateCurrency").toString()));
      }
      if ((jsonObj.get("casualHourlyRateCurrency") != null && !jsonObj.get("casualHourlyRateCurrency").isJsonNull()) && !jsonObj.get("casualHourlyRateCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `casualHourlyRateCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("casualHourlyRateCurrency").toString()));
      }
      if ((jsonObj.get("annualSalaryCurrency") != null && !jsonObj.get("annualSalaryCurrency").isJsonNull()) && !jsonObj.get("annualSalaryCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `annualSalaryCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("annualSalaryCurrency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayGradeUpdateRequestPayStepsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayGradeUpdateRequestPayStepsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayGradeUpdateRequestPayStepsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayGradeUpdateRequestPayStepsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PayGradeUpdateRequestPayStepsInner>() {
           @Override
           public void write(JsonWriter out, PayGradeUpdateRequestPayStepsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayGradeUpdateRequestPayStepsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayGradeUpdateRequestPayStepsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayGradeUpdateRequestPayStepsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayGradeUpdateRequestPayStepsInner
  * @throws IOException if the JSON string is invalid with respect to PayGradeUpdateRequestPayStepsInner
  */
  public static PayGradeUpdateRequestPayStepsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayGradeUpdateRequestPayStepsInner.class);
  }

 /**
  * Convert an instance of PayGradeUpdateRequestPayStepsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

