/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.DefaultRemunerationComponents;
import com.konfigthis.client.model.DefaultRemunerationComponentsList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultRemunerationComponentsApi
 */
@Disabled
public class DefaultRemunerationComponentsApiTest {

    private static DefaultRemunerationComponentsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DefaultRemunerationComponentsApi(apiClient);
    }

    /**
     * Find a Default Remuneration Component by ID
     *
     * Returns a single default remuneration component.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findByIdTest() throws ApiException {
        DefaultRemunerationComponents response = api.findById()
                .execute();
        // TODO: test validations
    }

    /**
     * List all Default Remuneration Components
     *
     * Returns a list of all [Default Remuneration Components](https://developers.intellihr.io/docs/v1/) recorded in the system.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        DefaultRemunerationComponentsList response = api.listAll()
                .execute();
        // TODO: test validations
    }

}
