/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.QualificationLibraryItems;
import com.konfigthis.client.model.QualificationLibraryItemsCreateRequest;
import com.konfigthis.client.model.QualificationLibraryItemsList;
import com.konfigthis.client.model.QualificationLibraryItemsPatchRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QualificationLibraryItemsApi
 */
@Disabled
public class QualificationLibraryItemsApiTest {

    private static QualificationLibraryItemsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new QualificationLibraryItemsApi(apiClient);
    }

    /**
     * Create a new Qualification Library Item
     *
     * Create a new [Qualification Library Item](https://developers.intellihr.io/docs/v1/) record with the provided data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewRecordTest() throws ApiException {
        String name = null;
        String qualificationTypeId = null;
        String qualificationExpiryType = null;
        String qualificationRegistrationNumberVisibilityType = null;
        String qualificationAttachmentRequirementType = null;
        Double expiryWarningPeriod = null;
        Boolean sendExpiryWarning = null;
        QualificationLibraryItems response = api.createNewRecord(name, qualificationTypeId, qualificationExpiryType, qualificationRegistrationNumberVisibilityType, qualificationAttachmentRequirementType)
                .expiryWarningPeriod(expiryWarningPeriod)
                .sendExpiryWarning(sendExpiryWarning)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete a Qualification Library Item by ID
     *
     * Deletes the [Qualification Library Items](https://developers.intellihr.io/docs/v1/) by the given ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIdTest() throws ApiException {
        api.deleteById()
                .execute();
        // TODO: test validations
    }

    /**
     * Find a Qualification Library Item by ID
     *
     * Returns a single [Qualification Library Item](https://developers.intellihr.io/docs/v1/) by its identifier.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findByIDTest() throws ApiException {
        QualificationLibraryItemsList response = api.findByID()
                .execute();
        // TODO: test validations
    }

    /**
     * List all Qualification Library Items
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllQualificationsTest() throws ApiException {
        QualificationLibraryItems response = api.getAllQualifications()
                .execute();
        // TODO: test validations
    }

    /**
     * Patch an existing Qualification Library Item
     *
     * Patch attributes of an existing [Qualification Library Items](https://developers.intellihr.io/docs/v1/) record with the provided data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRecordTest() throws ApiException {
        String name = null;
        String qualificationTypeId = null;
        String qualificationExpiryType = null;
        String qualificationRegistrationNumberVisibilityType = null;
        String qualificationAttachmentRequirementType = null;
        Double expiryWarningPeriod = null;
        Boolean sendExpiryWarning = null;
        QualificationLibraryItems response = api.updateRecord()
                .name(name)
                .qualificationTypeId(qualificationTypeId)
                .qualificationExpiryType(qualificationExpiryType)
                .qualificationRegistrationNumberVisibilityType(qualificationRegistrationNumberVisibilityType)
                .qualificationAttachmentRequirementType(qualificationAttachmentRequirementType)
                .expiryWarningPeriod(expiryWarningPeriod)
                .sendExpiryWarning(sendExpiryWarning)
                .execute();
        // TODO: test validations
    }

}
