/*
 * intelliHR Public API
 * You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)
 *
 * The version of the OpenAPI document: V1
 * Contact: support@intellihr.co
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.PersonDocumentsCreateRequest;
import com.konfigthis.client.model.PersonDocumentsCreateRequestPerson;
import com.konfigthis.client.model.PersonDocumentsCreateResponse;
import com.konfigthis.client.model.PersonDocumentsPatchRequest;
import com.konfigthis.client.model.PersonDocumentsPatchResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class PersonDocumentsDeprecatedApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PersonDocumentsDeprecatedApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public PersonDocumentsDeprecatedApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKey() == null) {
            throw new IllegalArgumentException("\"Authorization\" is required but no API key was provided. Please set \"Authorization\" with ApiClient#setApiKey(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createPresignedUploadUrlCall(PersonDocumentsCreateRequest personDocumentsCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = personDocumentsCreateRequest;

        // create path and map variables
        String localVarPath = "/person-documents";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call createPresignedUploadUrlValidateBeforeCall(PersonDocumentsCreateRequest personDocumentsCreateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'personDocumentsCreateRequest' is set
        if (personDocumentsCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'personDocumentsCreateRequest' when calling createPresignedUploadUrl(Async)");
        }

        return createPresignedUploadUrlCall(personDocumentsCreateRequest, _callback);

    }


    private ApiResponse<PersonDocumentsCreateResponse> createPresignedUploadUrlWithHttpInfo(PersonDocumentsCreateRequest personDocumentsCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = createPresignedUploadUrlValidateBeforeCall(personDocumentsCreateRequest, null);
        Type localVarReturnType = new TypeToken<PersonDocumentsCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createPresignedUploadUrlAsync(PersonDocumentsCreateRequest personDocumentsCreateRequest, final ApiCallback<PersonDocumentsCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createPresignedUploadUrlValidateBeforeCall(personDocumentsCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<PersonDocumentsCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreatePresignedUploadUrlRequestBuilder {
        private final PersonDocumentsCreateRequestPerson person;
        private final String filename;
        private final String mime;
        private final Integer size;
        private final String extension;

        private CreatePresignedUploadUrlRequestBuilder(PersonDocumentsCreateRequestPerson person, String filename, String mime, Integer size, String extension) {
            this.person = person;
            this.filename = filename;
            this.mime = mime;
            this.size = size;
            this.extension = extension;
        }

        /**
         * Build call for createPresignedUploadUrl
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Created Successfully </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            PersonDocumentsCreateRequest personDocumentsCreateRequest = buildBodyParams();
            return createPresignedUploadUrlCall(personDocumentsCreateRequest, _callback);
        }

        private PersonDocumentsCreateRequest buildBodyParams() {
            PersonDocumentsCreateRequest personDocumentsCreateRequest = new PersonDocumentsCreateRequest();
            personDocumentsCreateRequest.person(this.person);
            personDocumentsCreateRequest.filename(this.filename);
            personDocumentsCreateRequest.mime(this.mime);
            personDocumentsCreateRequest.size(this.size);
            personDocumentsCreateRequest.extension(this.extension);
            return personDocumentsCreateRequest;
        }

        /**
         * Execute createPresignedUploadUrl request
         * @return PersonDocumentsCreateResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Created Successfully </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public PersonDocumentsCreateResponse execute() throws ApiException {
            PersonDocumentsCreateRequest personDocumentsCreateRequest = buildBodyParams();
            ApiResponse<PersonDocumentsCreateResponse> localVarResp = createPresignedUploadUrlWithHttpInfo(personDocumentsCreateRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createPresignedUploadUrl request with HTTP info returned
         * @return ApiResponse&lt;PersonDocumentsCreateResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Created Successfully </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public ApiResponse<PersonDocumentsCreateResponse> executeWithHttpInfo() throws ApiException {
            PersonDocumentsCreateRequest personDocumentsCreateRequest = buildBodyParams();
            return createPresignedUploadUrlWithHttpInfo(personDocumentsCreateRequest);
        }

        /**
         * Execute createPresignedUploadUrl request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Created Successfully </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call executeAsync(final ApiCallback<PersonDocumentsCreateResponse> _callback) throws ApiException {
            PersonDocumentsCreateRequest personDocumentsCreateRequest = buildBodyParams();
            return createPresignedUploadUrlAsync(personDocumentsCreateRequest, _callback);
        }
    }

    /**
     * 
     * Create a presigned upload URL
     * @param personDocumentsCreateRequest  (required)
     * @return CreatePresignedUploadUrlRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created Successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public CreatePresignedUploadUrlRequestBuilder createPresignedUploadUrl(PersonDocumentsCreateRequestPerson person, String filename, String mime, Integer size, String extension) throws IllegalArgumentException {
        if (person == null) throw new IllegalArgumentException("\"person\" is required but got null");
        if (filename == null) throw new IllegalArgumentException("\"filename\" is required but got null");
            

        if (mime == null) throw new IllegalArgumentException("\"mime\" is required but got null");
            

        if (size == null) throw new IllegalArgumentException("\"size\" is required but got null");
        if (extension == null) throw new IllegalArgumentException("\"extension\" is required but got null");
            

        return new CreatePresignedUploadUrlRequestBuilder(person, filename, mime, size, extension);
    }
    private okhttp3.Call updateDocumentCall(PersonDocumentsPatchRequest personDocumentsPatchRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = personDocumentsPatchRequest;

        // create path and map variables
        String localVarPath = "/person-documents/{id}";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateDocumentValidateBeforeCall(PersonDocumentsPatchRequest personDocumentsPatchRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'personDocumentsPatchRequest' is set
        if (personDocumentsPatchRequest == null) {
            throw new ApiException("Missing the required parameter 'personDocumentsPatchRequest' when calling updateDocument(Async)");
        }

        return updateDocumentCall(personDocumentsPatchRequest, _callback);

    }


    private ApiResponse<PersonDocumentsPatchResponse> updateDocumentWithHttpInfo(PersonDocumentsPatchRequest personDocumentsPatchRequest) throws ApiException {
        okhttp3.Call localVarCall = updateDocumentValidateBeforeCall(personDocumentsPatchRequest, null);
        Type localVarReturnType = new TypeToken<PersonDocumentsPatchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call updateDocumentAsync(PersonDocumentsPatchRequest personDocumentsPatchRequest, final ApiCallback<PersonDocumentsPatchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateDocumentValidateBeforeCall(personDocumentsPatchRequest, _callback);
        Type localVarReturnType = new TypeToken<PersonDocumentsPatchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class UpdateDocumentRequestBuilder {
        private final String personId;
        private String filename;
        private Object uploadStatus;

        private UpdateDocumentRequestBuilder(String personId) {
            this.personId = personId;
        }

        /**
         * Set filename
         * @param filename The filename of the document. This will be used for display name. Includes extension. (optional)
         * @return UpdateDocumentRequestBuilder
         */
        public UpdateDocumentRequestBuilder filename(String filename) {
            this.filename = filename;
            return this;
        }
        
        /**
         * Set uploadStatus
         * @param uploadStatus The upload status of this [Document](https://developers.intellihr.io/docs/v1/). Enum: &#x60;SUCCESS&#x60;, &#x60;PENDING&#x60;, &#x60;FAILED&#x60;. (optional)
         * @return UpdateDocumentRequestBuilder
         */
        public UpdateDocumentRequestBuilder uploadStatus(Object uploadStatus) {
            this.uploadStatus = uploadStatus;
            return this;
        }
        
        /**
         * Build call for updateDocument
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            PersonDocumentsPatchRequest personDocumentsPatchRequest = buildBodyParams();
            return updateDocumentCall(personDocumentsPatchRequest, _callback);
        }

        private PersonDocumentsPatchRequest buildBodyParams() {
            PersonDocumentsPatchRequest personDocumentsPatchRequest = new PersonDocumentsPatchRequest();
            personDocumentsPatchRequest.personId(this.personId);
            personDocumentsPatchRequest.filename(this.filename);
            personDocumentsPatchRequest.uploadStatus(this.uploadStatus);
            return personDocumentsPatchRequest;
        }

        /**
         * Execute updateDocument request
         * @return PersonDocumentsPatchResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public PersonDocumentsPatchResponse execute() throws ApiException {
            PersonDocumentsPatchRequest personDocumentsPatchRequest = buildBodyParams();
            ApiResponse<PersonDocumentsPatchResponse> localVarResp = updateDocumentWithHttpInfo(personDocumentsPatchRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute updateDocument request with HTTP info returned
         * @return ApiResponse&lt;PersonDocumentsPatchResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public ApiResponse<PersonDocumentsPatchResponse> executeWithHttpInfo() throws ApiException {
            PersonDocumentsPatchRequest personDocumentsPatchRequest = buildBodyParams();
            return updateDocumentWithHttpInfo(personDocumentsPatchRequest);
        }

        /**
         * Execute updateDocument request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
            <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call executeAsync(final ApiCallback<PersonDocumentsPatchResponse> _callback) throws ApiException {
            PersonDocumentsPatchRequest personDocumentsPatchRequest = buildBodyParams();
            return updateDocumentAsync(personDocumentsPatchRequest, _callback);
        }
    }

    /**
     * 
     * Update a Document
     * @param personDocumentsPatchRequest  (required)
     * @return UpdateDocumentRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td>  </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public UpdateDocumentRequestBuilder updateDocument(String personId) throws IllegalArgumentException {
        if (personId == null) throw new IllegalArgumentException("\"personId\" is required but got null");
            if (personId != null && personId.length() < 36) {
              throw new IllegalArgumentException("Invalid value for personId. Length must be greater than or equal to 36.");
            }

        return new UpdateDocumentRequestBuilder(personId);
    }
}
